spin_manifest_version = 2

[application]
name = "kord-web"
version = "0.2.0"
authors = ["Aaron Roney <twitchax@gmail.com>"]
description = "Example project showing off Leptos with Axum, running as a `wasi:http` service."

[[trigger.http]]
route = "/..."
component = "kord-web"

[component.kord-web]
source = "target/wasm32-wasip2/release/kord_web.wasm"
allowed_outbound_hosts = []
environment = { LEPTOS_OUTPUT_NAME = "kord_web" }

[component.kord-web.build]
command = "cargo leptos build --release && LEPTOS_OUTPUT_NAME=kord_web cargo build --lib --target wasm32-wasip2 --release --no-default-features --features ssr"
watch = ["src/**/*.rs", "Cargo.toml"]